import type { Product } from "@/types/product";

const fmt = (n: number) => `$${n}`;

export const DEFAULT_PRODUCTS: Product[] = [
  {
    slug: "azwah-noir",
    name: "Azwah Noir",
    brand: "Azwah",
    category: "men",
    subtitle: "Eau de Parfum",
    notes: "Oud · Amber · White Musk",
    notePyramid: {
      top: ["Saffron", "Cardamom", "Bergamot"],
      heart: ["Oud Assam", "Rose Damascena", "Iris"],
      base: ["Amber", "White Musk", "Sandalwood Mysore"],
    },
    description: "Midnight elegance bottled. Bold, smoky, eternal.",
    longDescription:
      "Azwah Noir is our definitive masculine statement — built around aged Assam oud and Baltic amber, softened by white musk and Mysore sandalwood. Composed entirely in our atelier with ingredients we source and age ourselves. A fragrance for evenings, boardrooms, and moments that demand presence without noise.",
    priceFrom: 285,
    currency: "USD",
    sizes: [
      { ml: 50, price: 285, label: "50 ml" },
      { ml: 100, price: 420, label: "100 ml" },
    ],
    ingredients: ["Assam Oud", "Baltic Amber", "White Musk", "Mysore Sandalwood", "Kashmir Saffron"],
    images: [
      { id: "front", alt: "Azwah Noir bottle front view", variant: "bottle", accent: "noir" },
      { id: "detail", alt: "Azwah Noir cap and glass detail", variant: "detail", accent: "noir" },
      { id: "box", alt: "Azwah Noir gift packaging", variant: "box", accent: "noir" },
      { id: "lifestyle", alt: "Azwah Noir on marble surface", variant: "lifestyle", accent: "noir" },
    ],
    inStock: true,
    featured: true,
    isOwnBlend: true,
    deliveryDays: "2–4 business days",
    tags: ["Bestseller", "Own Blend", "Men"],
  },
  {
    slug: "azwah-rose",
    name: "Azwah Rose",
    brand: "Azwah",
    category: "women",
    subtitle: "Eau de Parfum",
    notes: "Rose · Sandalwood · Saffron",
    notePyramid: {
      top: ["Grasse Rose", "Pink Pepper", "Mandarin"],
      heart: ["Damask Rose", "Saffron", "Peony"],
      base: ["Sandalwood", "Amber", "Vanilla"],
    },
    description: "Velvet petals meet golden spice. Romantic and refined.",
    longDescription:
      "Hand-picked Grasse roses distilled at dawn form the heart of Azwah Rose — a composition that balances floral softness with saffron's leathery luminosity. Our own sandalwood infusion gives it a creamy, skin-like drydown that lingers for hours. Designed for women who prefer elegance over excess.",
    priceFrom: 265,
    currency: "USD",
    sizes: [
      { ml: 50, price: 265, label: "50 ml" },
      { ml: 100, price: 395, label: "100 ml" },
    ],
    ingredients: ["Grasse Rose", "Kashmir Saffron", "Mysore Sandalwood", "Baltic Amber"],
    images: [
      { id: "front", alt: "Azwah Rose bottle", variant: "bottle", accent: "rose" },
      { id: "detail", alt: "Rose gold cap detail", variant: "detail", accent: "rose" },
      { id: "box", alt: "Azwah Rose presentation box", variant: "box", accent: "rose" },
      { id: "lifestyle", alt: "Azwah Rose lifestyle", variant: "lifestyle", accent: "rose" },
    ],
    inStock: true,
    featured: true,
    isOwnBlend: true,
    deliveryDays: "2–4 business days",
    tags: ["Own Blend", "Women"],
  },
  {
    slug: "azwah-gold",
    name: "Azwah Gold",
    brand: "Azwah",
    category: "unisex",
    subtitle: "Parfum Extrême",
    notes: "Oud · Rose · Amber",
    notePyramid: {
      top: ["Oud", "Saffron", "Bergamot"],
      heart: ["Rose", "Jasmine Sambac", "Orris"],
      base: ["Amber", "Benzoin", "Patchouli"],
    },
    description: "Our rarest expression. Heirloom luxury in every drop.",
    longDescription:
      "Azwah Gold is the pinnacle of our house — a parfum extrême concentration with 28% aromatic compounds. Oud, rose, and amber in perfect equilibrium. Each batch is numbered and aged six months before release. A unisex masterpiece for collectors and connoisseurs.",
    priceFrom: 395,
    currency: "USD",
    sizes: [
      { ml: 30, price: 395, label: "30 ml" },
      { ml: 50, price: 580, label: "50 ml" },
    ],
    ingredients: ["Assam Oud", "Grasse Rose", "Baltic Amber", "Benzoin", "Orris Root"],
    images: [
      { id: "front", alt: "Azwah Gold bottle", variant: "bottle", accent: "gold" },
      { id: "detail", alt: "Gold flacon detail", variant: "detail", accent: "gold" },
      { id: "box", alt: "Azwah Gold coffret", variant: "box", accent: "gold" },
      { id: "lifestyle", alt: "Azwah Gold luxury display", variant: "lifestyle", accent: "gold" },
    ],
    inStock: true,
    featured: true,
    isOwnBlend: true,
    deliveryDays: "3–5 business days",
    tags: ["Limited", "Own Blend", "Unisex"],
  },
  {
    slug: "j-signature-oud",
    name: "J. Signature Oud",
    brand: "J. Perfume",
    category: "men",
    subtitle: "Eau de Parfum Intense",
    notes: "Oud · Leather · Tonka",
    notePyramid: {
      top: ["Grapefruit", "Pink Pepper", "Elemi"],
      heart: ["Oud", "Leather", "Geranium"],
      base: ["Tonka Bean", "Vanilla", "Sandalwood"],
    },
    description: "The iconic J. masculine oud — powerful, refined, unmistakable.",
    longDescription:
      "J. Signature Oud is among the most requested fragrances in our boutique. A masterful balance of smoky oud, supple leather, and warm tonka — the definitive J. Perfume expression for men. Authentic product, sealed and shipped with certificate of origin.",
    priceFrom: 320,
    currency: "USD",
    sizes: [
      { ml: 50, price: 320, label: "50 ml" },
      { ml: 100, price: 480, label: "100 ml" },
    ],
    ingredients: ["Natural Oud", "Leather Accord", "Tonka Bean", "Sandalwood"],
    images: [
      { id: "front", alt: "J. Signature Oud bottle", variant: "bottle", accent: "oud" },
      { id: "detail", alt: "J. Perfume cap engraving", variant: "detail", accent: "oud" },
      { id: "box", alt: "J. Perfume packaging", variant: "box", accent: "oud" },
      { id: "lifestyle", alt: "J. Signature Oud display", variant: "lifestyle", accent: "oud" },
    ],
    inStock: true,
    featured: true,
    deliveryDays: "2–4 business days",
    tags: ["J. Perfume", "Men", "Bestseller"],
  },
  {
    slug: "j-rose-elixir",
    name: "J. Rose Elixir",
    brand: "J. Perfume",
    category: "women",
    subtitle: "Eau de Parfum",
    notes: "Rose · Patchouli · Musk",
    notePyramid: {
      top: ["Lychee", "Raspberry", "Peony"],
      heart: ["Centifolia Rose", "Magnolia", "Freesia"],
      base: ["Patchouli", "White Musk", "Cashmeran"],
    },
    description: "J. Perfume's floral masterpiece — luminous, sensual, unforgettable.",
    longDescription:
      "J. Rose Elixir captures the house's signature rose in its most radiant form. Centifolia rose absolute layered with patchouli and a soft musk veil. A women's fragrance that transitions seamlessly from day to evening. Available for online order with gift wrapping.",
    priceFrom: 295,
    currency: "USD",
    sizes: [
      { ml: 50, price: 295, label: "50 ml" },
      { ml: 100, price: 445, label: "100 ml" },
    ],
    ingredients: ["Centifolia Rose", "Patchouli", "White Musk", "Lychee Accord"],
    images: [
      { id: "front", alt: "J. Rose Elixir bottle", variant: "bottle", accent: "rose" },
      { id: "detail", alt: "J. Rose Elixir detail", variant: "detail", accent: "rose" },
      { id: "box", alt: "J. Rose Elixir box", variant: "box", accent: "rose" },
      { id: "lifestyle", alt: "J. Rose Elixir lifestyle", variant: "lifestyle", accent: "rose" },
    ],
    inStock: true,
    featured: true,
    deliveryDays: "2–4 business days",
    tags: ["J. Perfume", "Women"],
  },
  {
    slug: "j-gold-prive",
    name: "J. Gold Privé",
    brand: "J. Perfume",
    category: "unisex",
    subtitle: "Parfum",
    notes: "Amber · Iris · Oud",
    notePyramid: {
      top: ["Saffron", "Mandarin", "Aldehydes"],
      heart: ["Iris", "Oud", "Jasmine"],
      base: ["Amber", "Vanilla", "Cedar"],
    },
    description: "The private blend of J. Perfume — exclusive to select retailers.",
    longDescription:
      "J. Gold Privé represents the highest tier of the J. Perfume portfolio. A parfum concentration with iris, oud, and golden amber — unisex and deeply luxurious. Azwah is an authorized partner; every bottle includes authentication and insured delivery.",
    priceFrom: 450,
    currency: "USD",
    sizes: [
      { ml: 30, price: 450, label: "30 ml" },
      { ml: 50, price: 680, label: "50 ml" },
    ],
    ingredients: ["Oud", "Orris Iris", "Amber", "Madagascar Vanilla"],
    images: [
      { id: "front", alt: "J. Gold Privé bottle", variant: "bottle", accent: "gold" },
      { id: "detail", alt: "J. Gold Privé gold cap", variant: "detail", accent: "gold" },
      { id: "box", alt: "J. Gold Privé coffret", variant: "box", accent: "gold" },
      { id: "lifestyle", alt: "J. Gold Privé luxury", variant: "lifestyle", accent: "gold" },
    ],
    inStock: true,
    featured: true,
    deliveryDays: "3–5 business days",
    tags: ["J. Perfume", "Unisex", "Exclusive"],
  },
  {
    slug: "maison-horizon",
    name: "Horizon",
    brand: "Maison Lumière",
    category: "men",
    subtitle: "Eau de Parfum",
    notes: "Vetiver · Cedar · Bergamot",
    notePyramid: {
      top: ["Bergamot", "Ginger", "Neroli"],
      heart: ["Vetiver", "Cedarwood", "Clary Sage"],
      base: ["Ambroxan", "Musk", "Oakmoss"],
    },
    description: "Clean woody freshness for the contemporary man.",
    longDescription:
      "Horizon by Maison Lumière is a versatile daily fragrance — bright bergamot opening into a vetiver-cedar heart. Perfect for office, travel, and casual elegance. Ships in protective packaging with 30-day satisfaction guarantee.",
    priceFrom: 195,
    currency: "USD",
    sizes: [
      { ml: 50, price: 195, label: "50 ml" },
      { ml: 100, price: 290, label: "100 ml" },
    ],
    ingredients: ["Haitian Vetiver", "Atlas Cedar", "Bergamot", "Ambroxan"],
    images: [
      { id: "front", alt: "Horizon bottle", variant: "bottle", accent: "jade" },
      { id: "detail", alt: "Horizon detail", variant: "detail", accent: "jade" },
      { id: "box", alt: "Horizon packaging", variant: "box", accent: "jade" },
    ],
    inStock: true,
    featured: false,
    deliveryDays: "2–4 business days",
    tags: ["Men"],
  },
  {
    slug: "essence-velvet-orchid",
    name: "Velvet Orchid",
    brand: "Essence Paris",
    category: "women",
    subtitle: "Eau de Parfum",
    notes: "Orchid · Vanilla · Honey",
    notePyramid: {
      top: ["Mandarin", "Honey", "Pink Pepper"],
      heart: ["Black Orchid", "Lotus", "Ylang-Ylang"],
      base: ["Vanilla", "Sandalwood", "Incense"],
    },
    description: "Dark floral opulence with a honeyed vanilla trail.",
    longDescription:
      "Velvet Orchid is Essence Paris at its most seductive — black orchid and honey over a vanilla-incense base. A statement fragrance for evening wear. Order online with complimentary sample vial.",
    priceFrom: 210,
    currency: "USD",
    sizes: [
      { ml: 50, price: 210, label: "50 ml" },
      { ml: 100, price: 315, label: "100 ml" },
    ],
    ingredients: ["Black Orchid", "Madagascar Vanilla", "Honey Absolute", "Incense"],
    images: [
      { id: "front", alt: "Velvet Orchid bottle", variant: "bottle", accent: "ivory" },
      { id: "detail", alt: "Velvet Orchid detail", variant: "detail", accent: "ivory" },
      { id: "box", alt: "Velvet Orchid box", variant: "box", accent: "ivory" },
    ],
    inStock: true,
    featured: false,
    deliveryDays: "2–4 business days",
    tags: ["Women"],
  },
  {
    slug: "azwah-discovery-set",
    name: "Discovery Set",
    brand: "Azwah",
    category: "accessories",
    subtitle: "Gift Collection · 5 × 10 ml",
    notes: "Noir · Rose · Gold · Oud · Musk",
    notePyramid: {
      top: ["Assorted"],
      heart: ["House Collection"],
      base: ["Travel Format"],
    },
    description: "Five house icons in travel size — the perfect introduction.",
    longDescription:
      "Our Discovery Set includes five 10 ml atomizers of Azwah Noir, Rose, Gold, plus two exclusive sample blends. Housed in a magnetic-closure coffret. Ideal for gifting or finding your signature before committing to a full bottle.",
    priceFrom: 145,
    currency: "USD",
    sizes: [{ ml: 50, price: 145, label: "5 × 10 ml" }],
    ingredients: ["House Blends", "Travel Atomizers"],
    images: [
      { id: "front", alt: "Discovery Set coffret", variant: "box", accent: "gold" },
      { id: "lifestyle", alt: "Discovery Set open", variant: "lifestyle", accent: "gold" },
    ],
    inStock: true,
    featured: false,
    isOwnBlend: true,
    deliveryDays: "2–4 business days",
    tags: ["Gift", "Own Blend"],
  },
  {
    slug: "luxury-atomizer-set",
    name: "Luxury Atomizer Set",
    brand: "Azwah",
    category: "accessories",
    subtitle: "Travel Accessories · 3 Piece",
    notes: "Refillable · Gold Finish",
    notePyramid: {
      top: ["Accessories"],
      heart: ["Travel"],
      base: ["Refillable"],
    },
    description: "Three refillable 10 ml atomizers in gold-finished cases.",
    longDescription:
      "Travel in style with our Luxury Atomizer Set — three leak-proof 10 ml refillable atomizers in brushed gold cases. Compatible with all Azwah and J. Perfume fragrances. Includes funnel and velvet pouch.",
    priceFrom: 85,
    currency: "USD",
    sizes: [{ ml: 30, price: 85, label: "3 × 10 ml" }],
    ingredients: ["Brushed Gold Case", "Refillable Glass"],
    images: [
      { id: "front", alt: "Luxury atomizer set", variant: "box", accent: "amber" },
      { id: "detail", alt: "Atomizer detail", variant: "detail", accent: "amber" },
    ],
    inStock: true,
    featured: false,
    deliveryDays: "2–4 business days",
    tags: ["Accessories", "Travel"],
  },
];

/** @deprecated Use getProducts() — kept as client-side fallback */
export const PRODUCTS = DEFAULT_PRODUCTS;

export function formatPrice(amount: number, currency = "USD"): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
  }).format(amount);
}

export { fmt };
